### ISSUE TITLE
Can't find files during cyclic dependency removal pass

### ISSUE THREAD

**Issue by joswhite** [DreierF/closure-es6-converter#1]
When running the converter I get the following error:
```bash
$ ./gradlew run

> Task :run
WARN: full_test_cases.js (C:\my-project\closure-es6-converter\es6-module-converter\..\closure-library\closure\goog\streams\full_test_cases.js) seems to be test-only, skipping file.
WARN: lite_test_cases.js (C:\my-project\closure-es6-converter\es6-module-converter\..\closure-library\closure\goog\streams\lite_test_cases.js) seems to be test-only, skipping file.
WARN: html_test_vectors.js (C:\my-project\closure-es6-converter\es6-module-converter\..\closure-library\closure\goog\html\sanitizer\html_test_vectors.js) seems to be test-only, skipping file.
WARN: test_agents.js (C:\my-project\closure-es6-converter\es6-module-converter\..\closure-library\closure\goog\labs\useragent\test_agents.js) seems to be test-only, skipping file.
Cyclic dependency is not required and therefore skipped in the merge process: date.js
Cyclic dependency is not required and therefore skipped in the merge process: datelike.js
Exception in thread "main" java.io.FileNotFoundException: ..\closure-library-converted\lib\date\date.js (The system cannot find the path specified)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at com.google.common.io.Files$FileByteSink.openStream(Files.java:192)
        at com.google.common.io.Files$FileByteSink.openStream(Files.java:180)
        at com.google.common.io.ByteSink$AsCharSink.openStream(ByteSink.java:149)
        at com.google.common.io.CharSink.write(CharSink.java:97)
        at eu.cqse.FileUtils.writeFileContent(FileUtils.java:80)
        at eu.cqse.CyclicDependencyRemovalPass.merge(CyclicDependencyRemovalPass.java:52)
        at eu.cqse.CyclicDependencyRemovalPass.process(CyclicDependencyRemovalPass.java:23)
        at eu.cqse.Es6ModuleMasterConverter.convert(Es6ModuleMasterConverter.java:180)
        at eu.cqse.Es6ModuleMasterConverter.main(Es6ModuleMasterConverter.java:44)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
2 actionable tasks: 2 executed
```
I have Java 11 installed properly, I ran "git submodule update --init" and "yarn install", then ran "./gradlew run" from the es6-module-converter folder. I haven't changed any files such as required-namespaces.txt. I'm running from Windows 10 in Git Bash. What do I need to do to get this converter to run properly?

**Comment by DreierF** [comment]
Interesting. I suspect it has something to do with Windows. I just tested it on my machine again and it works here (MacOS).
- Did creating of `closure-library-converted` work in the top level directory?
- Does it contain a copy of the closure library?
I have no easy way to debug this here, but should be fairly straight forward to open the project in IntelliJ or Eclipse and debug it where things go wrong.
@Dan1ve any ideas?

**Comment by joswhite** [comment]
It's successfully able to create `closure-library-converted`, which contains all the files I expect. I think it's forming the paths wrong. Instead of looking for `closure-library-converted\lib\date\date.js` it should be looking for `closure-library-converted\lib\closure\goog\date\date.js`.

**Comment by joswhite** [comment]
The issue is caused by line 160 of Es6ModuleMasterConverter.java. Because Windows paths use backslash, the code no longer works:
```
File dest = new File(file.toFile().getAbsolutePath().replace("third_party/", "")
  .replace("closure/goog/", ""));
```
If `/` is replaced with `\\`, this particular issue is fixed. Then we get a different error:

```bash
Exception in thread "main" java.io.IOException: Cannot run program "../node_modules/.bin/tsc": CreateProcess error=19 3, %1 is not a valid Win32 application
                                                 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
                                                 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
                                                 at java.base/java.lang.Runtime.exec(Runtime.java:591)
                                                 at java.base/java.lang.Runtime.exec(Runtime.java:450)
                                                 at eu.cqse.Es6ModuleMasterConverter.runTS(Es6ModuleMasterConverter.java:119)
                                                 at eu.cqse.Es6ModuleMasterConverter.generateTSDeclarationFiles(Es6ModuleMasterConverter.java:104)
                                                 at eu.cqse.Es6ModuleMasterConverter.main(Es6ModuleMasterConverter.java:46)                                    
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
                                                 at java.base/java.lang.ProcessImpl.create(Native Method)
                                                 at java.base/java.lang.ProcessImpl.(ProcessImpl.java:478)
                                                 at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
                                                 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)                                                 ... 6 more
--
```

This error is probably not too difficult to solve; we just need to use the actual tsc executable instead of the Bash script designed to execute it. On Windows, Bash scripts are not considered executable, neither are bat scripts. Of course, this is the 2nd Windows issue I found. There are probably more of them.

Are there any plans to support Windows for this project in the future? Maybe I should just try compiling on Linux or fixing the errors myself?

**Comment by Dan1ve** [comment]
I was able to run the converter a while back on Windows, so hopefully not that many issues remain (if any).
Regarding the last error, this can usually be resolved by referencing `tsc.cmd` instead of just `tsc`. So this might be a quick fix for you @joswhite , but I can't test it right now.

**Comment by joswhite** [comment]
Ok thanks. I will go ahead and close this. Maybe we can mention in the README that Windows doesn't work without a few tweaks

**Comment by joswhite** [comment]
I ended up using Linux and was able to successfully convert my Closure project & the portion of the Closure library it used to ES6 (total was over 100k LOC). It took a few hundred hours to get the code compatible with the converter & update a few things in the converter to work with my code, but it was worth it. Thanks!

**Comment by DreierF** [comment]
Glad to hear you found it helpful 🙂

**Comment by Dan1ve** [comment]
That's great @joswhite ! 👍
